// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGcayd-YHWtei1uP1_78JA5xGTZYLKJvs',
    appId: '1:346605474551:web:9d6ac8da6a54b98205b9f2',
    messagingSenderId: '346605474551',
    projectId: 'metrobike-ec82b',
    authDomain: 'metrobike-ec82b.firebaseapp.com',
    storageBucket: 'metrobike-ec82b.appspot.com',
    measurementId: 'G-X8RZY602PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGP9bM7cBYXEoPP7uhGVUU1mmwDeSeyXg',
    appId: '1:346605474551:android:9d511327e51bf47f05b9f2',
    messagingSenderId: '346605474551',
    projectId: 'metrobike-ec82b',
    storageBucket: 'metrobike-ec82b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMWq3osW6IyUr9pfHngQ2EimxuLmNB_JM',
    appId: '1:346605474551:ios:534ffa7da2b76aad05b9f2',
    messagingSenderId: '346605474551',
    projectId: 'metrobike-ec82b',
    storageBucket: 'metrobike-ec82b.appspot.com',
    iosClientId: '346605474551-arbe2u5m43hunomihcct3s0ho44a4bna.apps.googleusercontent.com',
    iosBundleId: 'com.metrobike.metrobike',
  );
}
